<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- Wörterbuch der Indogermanischen Sprachen: --> 
<!-- Dritter Teil: Wortschatz der Germanischen Spracheinheit -->
<!-- by Fick, Falk and Torp 1909 -->
<!-- Online edition by Sean Crist -->
<!-- kurisuto@unagi.cis.upenn.edu -->

<!-- log: -->
<!-- Dieter Studer changed Sean Crist's encoding of Greek ('<old>') to Unicode entities ('<new>') -->
<!-- Dieter Studer added the <lm>-Tags that mark the Germanic lemmata -->
<!-- Dieter Studer had a first go at marking up the Old English word forms (pilot) -->
<!-- Dieter Studer had a go at mixing the errata section into the main text (very time-consuming!) -->
<!-- <nb1> denotes text that has to be added -->
<!-- <nb0> denotes text that has to be deleted -->

<!-- Last modified 30 May 2006 -->

<!DOCTYPE document [
 
<!ELEMENT document (main, nachtraege)>

<!ELEMENT introduction (frontpage, foreword)>

<!ELEMENT main (entry | ergentry | pageheader | letterheader)+>
<!ELEMENT nachtraege (entry | pageheader | letterheader)+>

<!ELEMENT entry (#PCDATA | pagebreak | ERR | UNCERTAIN | QUESTIONABLE | PREMODERN_SPELLING | gr | oe | oe1 | lm | nb1 | nb0 )*>
<!-- 'ergentry' contains entries that have been added in "Nachträge und Berichtigungen". -->
<!ELEMENT ergentry (#PCDATA | pagebreak | ERR | UNCERTAIN | QUESTIONABLE | PREMODERN_SPELLING | gr | oe | oe1 | lm)*>
<!-- "Nachträge und Berichtigungen" are not yet incorporated completely -->
<!-- 'nb1' contains parts to be added when incorporating "Nachträge und Berichtigungen" -->
<!ELEMENT nb1 (#PCDATA | ERR | UNCERTAIN | QUESTIONABLE | PREMODERN_SPELLING | gr | oe | oe1 | lm)*>
<!-- 'nb0' contains parts to be removed when incorporating "Nachträge und Berichtigungen" -->
<!ELEMENT nb0 (#PCDATA | pagebreak | ERR | UNCERTAIN | QUESTIONABLE | PREMODERN_SPELLING | gr | oe | oe1 | lm)*>
<!ELEMENT pageheader (#PCDATA | ERR)*>
<!ELEMENT letterheader (#PCDATA)>
<!-- 'gr' contains greek word forms -->
<!ELEMENT gr (new, old)>

<!ELEMENT ERR EMPTY>
<!ELEMENT UNCERTAIN EMPTY>
<!ELEMENT QUESTIONABLE EMPTY>
<!ELEMENT PREMODERN_SPELLING EMPTY>
<!ELEMENT pagebreak EMPTY>
<!ELEMENT new (#PCDATA)>
<!ELEMENT old (#PCDATA)>
<!-- 'oe' contains Old English word forms -->
<!ELEMENT oe (#PCDATA)>
<!-- 'oe1' contains Old English word forms that are not part of the printing text -->
<!ELEMENT oe1 (#PCDATA)>
<!-- 'lm' contains the Germanic word forms that are typeset bold in the original -->
<!ELEMENT lm (#PCDATA)>

<!ATTLIST pageheader
       id CDATA ""
       pagenum_click CDATA ""
       upper_right_click CDATA ""
       lower_right_click CDATA ""
>

<!ATTLIST entry
       id CDATA ""
       click CDATA ""
       parent CDATA ""
       indentation CDATA ""
       semantic_class CDATA ""
       second_id CDATA ""
       second_click CDATA ""
>

<!ATTLIST ergentry
       id CDATA ""
       click CDATA ""
       parent CDATA ""
       indentation CDATA ""
       semantic_class CDATA ""
       second_id CDATA ""
       second_click CDATA ""
>

<!ATTLIST letterheader
       id CDATA ""
       click CDATA ""
       parent CDATA ""
       semantic_class CDATA ""
       second_id CDATA ""
       second_click CDATA ""
>

<!ATTLIST PREMODERN_SPELLING
       mod CDATA ""
>

<!ATTLIST ERR
       by CDATA ""
       corr CDATA ""
>

<!ENTITY a-acute-hook "&amp;a-acute-hook;">
<!ENTITY a-circ-acute "&amp;a-circ-acute;">
<!ENTITY a-hachek "&amp;a-hachek;">
<!ENTITY a-hook "&amp;a-hook;">
<!ENTITY a-long "&amp;a-long;">
<!ENTITY a-long-acute "&amp;a-long-acute;">
<!ENTITY a-long-short "&amp;a-long-short;">
<!ENTITY a-odot "&amp;a-odot;">
<!ENTITY a-odot-acute "&amp;a-odot-acute;">
<!ENTITY a-ohook "&amp;a-ohook;">
<!ENTITY a-short "&amp;a-short;">
<!ENTITY a-tilde "&amp;a-tilde;">
<!ENTITY a-udot "&amp;a-udot;">
<!ENTITY a-uml-circ "&amp;a-uml-circ;">
<!ENTITY aelig-circ "&amp;aelig-circ;">
<!ENTITY b-bar "&amp;b-bar;">
<!ENTITY beta "&amp;beta;">
<!ENTITY c-acute "&amp;c-acute;">
<!ENTITY c-hachek "&amp;c-hachek;">
<!ENTITY c-hachek-udot "&amp;c-hachek-udot;">
<!ENTITY c-udot "&amp;c-udot;">
<!ENTITY chi "&amp;chi;">
<!ENTITY close-square-bracket "&amp;close-square-bracket;">
<!ENTITY d-bar "&amp;d-bar;">
<!ENTITY d-udot "&amp;d-udot;">
<!ENTITY dash-acute "&amp;dash-acute;">
<!ENTITY dash-uncertain "&amp;dash-uncertain;">
<!ENTITY delta "&amp;delta;">
<!ENTITY e-acute-hook "&amp;e-acute-hook;">
<!ENTITY e-circ-acute "&amp;e-circ-acute;">
<!ENTITY e-hachek "&amp;e-hachek;">
<!ENTITY e-hook "&amp;e-hook;">
<!ENTITY e-long "&amp;e-long;">
<!ENTITY e-long-hook "&amp;e-long-hook;">
<!ENTITY e-long-short "&amp;e-long-short;">
<!ENTITY e-odot "&amp;e-odot;">
<!ENTITY e-odot-acute "&amp;e-odot-acute;">
<!ENTITY e-odot-tilde "&amp;e-odot-tilde;">
<!ENTITY e-ohook "&amp;e-ohook;">
<!ENTITY e-short "&amp;e-short;">
<!ENTITY e-sub "&amp;e-sub;">
<!ENTITY e-super "&amp;e-super;">
<!ENTITY e-tilde "&amp;e-tilde;">
<!ENTITY e-tilde-hook "&amp;e-tilde-hook;">
<!ENTITY e-udot "&amp;e-udot;">
<!ENTITY e-uml-acute "&amp;e-uml-acute;">
<!ENTITY e-uml-tilde "&amp;e-uml-tilde;">
<!ENTITY epsilon "&amp;epsilon;">
<!ENTITY epsilon-long "&amp;epsilon-long;">
<!ENTITY g-acute "&amp;g-acute;">
<!ENTITY g-circ "&amp;g-circ;">
<!ENTITY g-ocomma "&amp;g-ocomma;">
<!ENTITY h-udot "&amp;h-udot;">
<!ENTITY highquote "&amp;highquote;">
<!ENTITY i-circ-acute "&amp;i-circ-acute;">
<!ENTITY i-hook "&amp;i-hook;">
<!ENTITY i-long "&amp;i-long;">
<!ENTITY i-long-acute "&amp;i-long-acute;">
<!ENTITY i-long-short "&amp;i-long-short;">
<!ENTITY i-nonsyllabic "&amp;i-nonsyllabic;">
<!ENTITY i-oring "&amp;i-oring;">
<!ENTITY i-oring-acute "&amp;i-oring-acute;">
<!ENTITY i-oring-tilde "&amp;i-oring-tilde;">
<!ENTITY i-short "&amp;i-short;">
<!ENTITY i-tilde "&amp;i-tilde;">
<!ENTITY i-tilde-hook "&amp;i-tilde-hook;">
<!ENTITY j-hachek "&amp;j-hachek;">
<!ENTITY k-cedil "&amp;k-cedil;">
<!ENTITY k-circ "&amp;k-circ;">
<!ENTITY k-ocomma "&amp;k-ocomma;">
<!ENTITY l-bar "&amp;l-bar;">
<!ENTITY l-ocomma "&amp;l-ocomma;">
<!ENTITY l-tilde "&amp;l-tilde;">
<!ENTITY l-udot "&amp;l-udot;">
<!ENTITY l-uring "&amp;l-uring;">
<!ENTITY lambda "&amp;lambda;">
<!ENTITY left-half-ring "&amp;left-half-ring;">
<!ENTITY lowquote "&amp;lowquote;">
<!ENTITY m-odot "&amp;m-odot;">
<!ENTITY m-tilde "&amp;m-tilde;">
<!ENTITY m-udot "&amp;m-udot;">
<!ENTITY m-uring "&amp;m-uring;">
<!ENTITY n-acute "&amp;n-acute;">
<!ENTITY n-ocomma "&amp;n-ocomma;">
<!ENTITY n-odot "&amp;n-odot;">
<!ENTITY n-udot "&amp;n-udot;">
<!ENTITY n-uring "&amp;n-uring;">
<!ENTITY o-circ-acute "&amp;o-circ-acute;">
<!ENTITY o-circ-hook "&amp;o-circ-hook;">
<!ENTITY o-hook "&amp;o-hook;">
<!ENTITY o-long "&amp;o-long;">
<!ENTITY o-long-acute "&amp;o-long-acute;">
<!ENTITY o-long-short "&amp;o-long-short;">
<!ENTITY o-short "&amp;o-short;">
<!ENTITY o-uml-circ "&amp;o-uml-circ;">
<!ENTITY oelig "&amp;oelig;">
<!ENTITY open-square-bracket "&amp;open-square-bracket;">
<!ENTITY otilde "&amp;otilde;">
<!ENTITY q-bar "&amp;q-bar;">
<!ENTITY r-acute-udot "&amp;r-acute-udot;">
<!ENTITY r-hachek "&amp;r-hachek;">
<!ENTITY r-long "&amp;r-long;">
<!ENTITY r-odot "&amp;r-odot;">
<!ENTITY r-runic "&amp;r-runic;">
<!ENTITY r-tilde "&amp;r-tilde;">
<!ENTITY r-udot "&amp;r-udot;">
<!ENTITY r-uring "&amp;r-uring;">
<!ENTITY s-acute "&amp;s-acute;">
<!ENTITY s-hachek "&amp;s-hachek;">
<!ENTITY s-ocomma "&amp;s-ocomma;">
<!ENTITY s-tall "&amp;s-tall;">
<!ENTITY s-udot "&amp;s-udot;">
<!ENTITY schwa "&amp;schwa;">
<!ENTITY sup4 "&amp;sup4;">
<!ENTITY t-ocomma "&amp;t-ocomma;">
<!ENTITY t-udot "&amp;t-udot;">
<!ENTITY theta "&amp;theta;">
<!ENTITY u-circ-acute "&amp;u-circ-acute;">
<!ENTITY u-hachek "&amp;u-hachek;">
<!ENTITY u-long "&amp;u-long;">
<!ENTITY u-long-acute "&amp;u-long-acute;">
<!ENTITY u-long-short "&amp;u-long-short;">
<!ENTITY u-nonsyllabic "&amp;u-nonsyllabic;">
<!ENTITY u-odot "&amp;u-odot;">
<!ENTITY u-oring "&amp;u-oring;">
<!ENTITY u-oring-acute "&amp;u-oring-acute;">
<!ENTITY u-oring-tilde "&amp;u-oring-tilde;">
<!ENTITY u-short "&amp;u-short;">
<!ENTITY u-super "&amp;u-super;">
<!ENTITY u-tilde "&amp;u-tilde;">
<!ENTITY u-uml-circ "&amp;u-uml-circ;">
<!ENTITY upsilon "&amp;upsilon;">
<!ENTITY v-udot "&amp;v-udot;">
<!ENTITY w-circ "&amp;w-circ;">
<!ENTITY y-circ "&amp;y-circ;">
<!ENTITY y-short "&amp;y-short;">
<!ENTITY y-tilde "&amp;y-tilde;">
<!ENTITY yacute "&amp;yacute;">
<!ENTITY z-hachek "&amp;z-hachek;">
<!ENTITY z-hook "&amp;z-hook;">
<!ENTITY z-odot "&amp;z-odot;">

]>

<document>

<main>

<pageheader id="b0001:0" pagenum_click="1210,63" upper_right_click="1206,670" lower_right_click="1206,2120">â - aihti. 1</pageheader>

<letterheader id="b0001:1">A.</letterheader>

<entry id="b0001:2" indentation="1" click="60,670"><lm>â</lm> Interjection. ahd. â, angehängt hilf-â, nein-â, vorgesetzt â-hei, vor- und nachgesetzt â-hei-â. lit. á, á á Interjection. - gr. <gr><new>&#x1F00;, &#x1F04;</new><old>a), a)'</old></gr>. - lat. â, âh. - skr. â Interj.</entry>

<entry id="b0001:3" indentation="1" click="60,813"><lm>ajja</lm> (?) n. Ei. krimgot. ada (aus addja pl.); an. egg n.; as. ei, ags. <oe>&aelig-circ;g</oe> (= aij-); ahd. mhd. ei n., nhd. Ei. Vgl. asl. aje, jaje n. Ei. Entfernter verwandt sind gr. <gr><new>&#x1FA0;&#x1F79;&#x03BD;</new><old>w)?o'n</old></gr> lat. ôvum.</entry>

<entry id="b0001:4" indentation="1" click="63,953" semantic_class="tr"><lm>aik-</lm>, <lm>aikô</lm> f. Eiche. an. eik pl. eikr f. Eiche; as. êk f., ags. <oe>âc</oe> f. (eng. oak); ahd. eih, mhd. eich, eiche f., nhd. Eiche. Vgl. gr. <gr><new>&#x03B1;&#x1F30;&#x03B3;&#x1F77;&#x03BB;&#x03C9;&#x03C8;</new><old>ai)gi'lwy</old></gr> eine Eichenart, <gr><new>&#x03BA;&#x03C1;&#x1F71;&#x03C4;&#x03B1;&#x03B9;&#x03B3;&#x03BF;&#x03C2;</new><old>kra'taigos</old></gr> unbestimmte Baumart, wohl auch lat. aesculus Speiseeiche (aus aig-sklo-). Vielleicht ig. Wz. aig in skr. éjati rührt sich, erbebt; vgl. an. eikinn gewaltsam, ags. <oe>âcol</oe> aufgeregt, erschrocken; nasaliert in skr. i&n-odot;gati regt sich, i&n-odot;ga beweglich. S. ik-verna.</entry>

<entry id="b0001:5" indentation="1" click="63,1270"><lm>aikan</lm> <lm>eaik</lm> sprechen, sagen. g. afaikan -aíaik verläugnen; ahd. eihhân, eichôn, mhd. eichen zusprechen, zueignen.</entry>

<entry id="b0001:6" indentation="1" click="63,1356">(<lm>aihv</lm>) heischen. In g. aihtrôn sich erbitten, erbetteln. Vgl. lett. aizin&a-long;t herbeirufen, einladen. - gr. <gr><new>&#x03B1;&#x1F30;&#x03C4;&#x1F73;&#x03C9;</new><old>ai)te'w</old></gr> fordere, <gr><new>&#x03B1;&#x1F30;&#x03BA;&#x1F71;&#x03B6;&#x03B5;&#x03B9; &#x03BA;&#x03B1;&#x03BB;&#x03B5;&#x1FD6;</new><old>ai)ka'zei kalei=</old></gr> Hesych.</entry>

<entry id="b0001:7" indentation="1" click="60,1453"><lm>aigan</lm> <lm>aih</lm> <lm>aihtô-</lm> <lm>aigana</lm> haben, besitzen. g. aigan aih aihta; an. eiga â âtta haben, besitzen; as. êgan, ags. <oe>âgan</oe> (engl. owe); ahd. eigan, mhd. eigen haben, besitzen. Vgl. skr. îç î&s-udot;&t-udot;e zu eigen haben, mächtig, Herr sein über, zend. iç.</entry>

<entry id="b0001:8" indentation="2" parent="1:7" click="133,1640"><lm>aigana</lm>, <lm>aigina</lm> eigen, eigtl. part. praet. von aigan, sbst. n. das Eigen, Eigentum. an. eiginn eigen, eigentümlich; as. êgan, ags. <oe>âgen</oe>, engl. own; ahd. eigan, mhd. nhd. eigen. g. aigin n. Eigentum, Vermögen; an. eigin n. dass.; as. êgan n., ags. <oe>âgen</oe> n.; ahd. eigan, mhd. eigen n. Eigentum, besonders Grundbesitz, nhd. mein Eigen. Davon aiganôn (aiginôn) in an. eigna a&d-bar;a zueignen; ags. <oe>âgnian</oe>, besitzen, zu eigen machen; ahd. eiginên, mhd. eigenen zu eigen machen, nhd. an-eignen.</entry>

<entry id="b0001:9" indentation="2" parent="1:7" click="130,1996" semantic_class="i3"><lm>aihti</lm> f. Besitz. g. aihts f. Eigentum; an. æt, âtt f. Geschlecht, Generation, Himmelsgegend; ags. <oe>âht</oe>; ahd. êht f. Besitz, Eigentum. Vgl. ir. icht Nachkommenschaft, Stamm.</entry>

<pageheader id="b0002:0" pagenum_click="83,53" upper_right_click="1213,150" lower_right_click="1196,2113">2 aig - aida.</pageheader>

<entry id="b0002:1" indentation="1" click="83,146">(<lm>aig</lm>) spitzig sein. In aigina = an. eigin n. (?) eben hervorgesprossener Saatkeim, schwed. mundartl. äjel m. Vgl. gr. <gr><new>&#x03B1;&#x1F30;&#x03BA;&#x03BB;&#x03BF;&#x03B9; &#x03B1;&#x1F31; &#x03B3;&#x03C9;&#x03BD;&#x1F77;&#x03B1;&#x03B9; &#x03C4;&#x03BF;&#x1FE6; &#x03B2;&#x1F73;&#x03BB;&#x03BF;&#x03C5;&#x03C2;</new><old>ai)kloi ai( gwni'ai tou= be'lous</old></gr>. - preuss. ayculo f. Nadel; asl. igla f. Nadel. Vgl. auch germ. îgila (s. eg.).</entry>

<entry id="b0002:2" indentation="1" click="76,326" semantic_class="i3">(<lm>aigv</lm>) Scham fühlen. Germanisch in aiviskia.</entry>

<entry id="b0002:3" indentation="2" parent="2:2" click="146,386"><lm>aiviskia</lm> (aus <lm>aigviskia</lm>) n. Schande. g. aiviski n. Schande, Beschämung, unaivisks schandlos, aiviskôn unanständig handeln (davon sp.-port. asco Ekel); ags. <oe>&aelig-circ;wisc</oe> n. Schande, Vergehen, adj. schamlos, nnd. eisk, aisch fürchterlich, ekelhaft, garstig; mhd. eisch häßlich, abscheulich. Hierher mnd. eichelen, êchelen, êgelen (aus aivilôn) ekeln, widerwärtig sein (davon entlehnt nhd. ekeln). Vgl. gr. <gr><new>&#x03B1;&#x1F36;&#x03C3;&#x03C7;&#x03BF;&#x03C2;</new><old>ai)=sxos</old></gr> Schande.</entry>

<entry id="b0002:4" indentation="1" click="73,696">(<lm>ait</lm>) schwellen. Vgl. ksl. jadro n. (&lt; &e-hachek;dro) Bausch, Schwellung, jad&u-short; m. Gift. - gr. <gr><new>&#x03BF;&#x1F36;&#x03B4;&#x03BC;&#x03B1;</new><old>oi)=dma</old></gr> n. Schwall, <gr><new>&#x03BF;&#x1F34;&#x03B4;&#x1F73;&#x03C9;</new><old>oi)'de'w</old></gr> schwelle, <gr><new>&#x03BF;&#x1F36;&#x03B4;&#x03BF;&#x03C2;</new><old>oi)=dos</old></gr> n. Geschwulst. - lat. aemidus tumidus (aus aedm-). - arm. aitumn Geschwulst, aitnum schwelle.</entry>

<entry id="b0002:5" indentation="2" parent="2:4" click="140,890" semantic_class="i3"><lm>aita</lm> m. Geschwür. ahd. ei&z-hook;, mhd. ei&z-hook; m. Geschwür, Eiterbeule. Vgl. das Dim. an. eitill m. Drüse, Knorren am Baum usw. = mhd. ei&z-hook;el kleines eiterndes Geschwür. Hierzu auch an. eista n. Hode (aus idg. *oid-s-to-, vgl. gr. <gr><new>&#x03BF;&#x1F30;&#x03B4;&#x03BF;&#x03C2;</new><old>oi)dos</old></gr> n.), womit vielleicht zu vergleichen asl. isto n. Hode pl. Nieren, das aber andrerseits von lit. ínkstas Niere, Hode schwer zu trennen ist.<nb1> Bezzenberger trennt an. eitill, mhd. ei&z-hook;el von der ig. Wz. oid, und stellt sie zu lett. idra faules Mark eines Baumes, idr&u-oring;t einen faulen Kern bekommen (B. B. XXVII 112). Kaum richtig.</nb1></entry>

<entry id="b0002:6" indentation="2" parent="2:4" click="136,1160"><lm>aitra</lm> n. Gift. an. eitr n. Gift, eitr-ormr m. Giftschlange; as. eitir, êttor n., ags. <oe>âtor</oe>, <oe>âttor</oe> n.; ahd. eitar, eittar, mhd. eiter n. Gift, mhd. eiterslange f. Giftschlange, nhd. Eiter m. Vgl. asl. jad&u-short; m. Gift, jadro n. Schwellung, Bausch.</entry>

<entry id="b0002:7" indentation="1" click="63,1346" semantic_class="so"><lm>aiþa</lm> m. Eid. g. aiþs m. Eid; an. ei&d-bar;r m.; as. êth, êd, ags. <oe>âþ</oe> m., engl. oath; ahd. eid, mhd. eit g. eides, nhd. Eid m. Vgl. ir. oeth m. Eid.</entry>

<entry id="b0002:8" indentation="2" parent="2:7" click="136,1486" semantic_class="fa"><lm>aiþuma</lm> m. Schwiegersohn.<ERR by="crist"/> ags. <oe>âþum</oe> m. Schwiegersohn, Schwager, afries. âthom; ahd. eidum, Schwiegersohn,<ERR by="crist"/> mhd. eidem Schwiegersohn, Schwiegervater, nhd. Eidam. Vgl. zum Bedeutungsverhältnis g. liugan heiraten: ir. luge Eid.</entry>

<entry id="b0002:9" indentation="1" click="60,1670" semantic_class="fa"><lm>aiþî(n)</lm> f. Mutter. g. aiþei f. Mutter. Vgl. an. edda Großmutter<nb0> (aus aiþiþôn?)</nb0><nb1>, kaum aus germ. *aiþiþôn, sondern es hat hypokoristische Konsonantenverdoppelung</nb1>; ahd. (fuotar)eidî, mhd. eide Mutter. Lallwort. Vgl. ir. aite Vater.</entry>

<entry id="b0002:10" indentation="1" click="60,1813">(<lm>aid</lm>) brennen. Vgl. ail. Vgl. gr. <gr><new>&#x03B1;&#x1F34;&#x03D1;&#x03C9;</new><old>ai)'qw</old></gr> flamme, <gr><new>&#x03B1;&#x1F30;&#x03D1;&#x1F75;&#x03C1;, &#x03B1;&#x1F34;&#x03D1;&#x03C1;&#x03B1;, &#x03B1;&#x1F34;&#x03D1;&#x03C1;&#x03B9;&#x03BF;&#x03C2;</new><old>ai)qh'r, ai)'qra, ai)'qrios</old></gr>. - lat. aedes, aestus, aestas. - ir. aed Feuer. Schwundstufe îdh, idh. Vgl. gr. <gr><new>&#x1F30;&#x03D1;&#x03B1;&#x1F77;&#x03BD;&#x03BF;&#x03BC;&#x03B1;&#x03B9;, &#x1F30;&#x03D1;&#x03B1;&#x03C1;&#x1F79;&#x03C2;</new><old>i)qai'nomai, i)qaro's</old></gr> - skr. idh inddhe zündet an, entflammt, idhma m. Brennholz.</entry>

<entry id="b0002:11" indentation="2" parent="2:10" click="126,2003"><lm>aida</lm> m. Brand.<nb0> and. êd,</nb0> ags. <oe>âd</oe>; ahd. mhd. eit m. Glut, Scheiterhaufen. Vgl. gr. <gr><new>&#x03B1;&#x1F36;&#x03D1;&#x03BF;&#x03C2;</new><old>ai)=qos</old></gr> m. Brand, <gr><new>&#x03B1;&#x1F30;&#x03D1;&#x1F79;&#x03C2;</new><old>ai)qo's</old></gr> verbrannt. - skr. édha m. Brennholz.</entry>

<pageheader id="b0003:0" pagenum_click="1226,56" upper_right_click="1226,150" lower_right_click="1223,2113">aisô(n) - ailda. 3</pageheader>

<entry id="b0003:1" indentation="2" parent="2:10" click="156,150" semantic_class="i3"><lm>aisô(n)</lm> f. (aus *aidh-s-â) Feuer, Feuerstätte, an. eisa f. Feuer, norw. mundartl. eisa f. Feuerstätte; mnd. êse f. Esse, Feuerherd. Hierzu auch ags. <oe>âst</oe> m. Ofen (engl. oast), ndl. eest (aus idg. aidh-s-to). Unverwandt ahd. essa, siehe as. Vgl. gr. <gr><new>&#x03B1;&#x1F36;&#x03D1;&#x03BF;&#x03C2;</new><old>ai)=qos</old></gr> n. Glut, Brand. - skr. édhas n. Brennholz.</entry>

<entry id="b0003:2" indentation="2" parent="2:10" click="156,376"><lm>îdala</lm> urspr. scheinend. as. îdal, îdil eitel, leer, ags. <oe>îdel</oe> leer, nichtig, ledig (engl. idle); ahd. îtal, mhd. îtel leer, ledig, eitel vergeblich, nhd. eitel. Die Bedeutungen haben sich wohl aus einer Grundbedeutung »scheinbar« entwickelt. Vgl. gr. <gr><new>&#x1F30;&#x03D1;&#x03B1;&#x03C1;&#x1F79;&#x03C2;</new><old>i)qaro's</old></gr> rein, heiter. - skr. îdhríya zum heitern Himmel gehörig.</entry>

<entry id="b0003:3" indentation="1" click="86,620" semantic_class="nu"><lm>aina</lm> einer. g. ains einer; an. einn einer, Zahlwort, Adj., Pron.; as. ên, afries. ên, ân, ags. <oe>ân</oe> (engl. one); ahd. mhd. ein Zahlwort, Adj., Pron., Artikel. Vgl. preuss. ainas, lit. v&e-uml-acute;nas einer; asl. in&u-short;. - gr. <gr><new>&#x1F44;&#x03B9;&#x03BD;&#x03B7;</new><old>o)'inh</old></gr> - lat. oinos, ûnus. - altir. oen. - skr. ena heißt er, dieser: vgl. zend aêva einer.</entry>

<entry id="b0003:4" indentation="2" parent="3:3" click="153,850"><lm>ainahan</lm>, <lm>ainagan</lm> einzig, allein, g. ainaha einzig; an. einga einzig, allein; ags. <oe>ânga</oe> dass. Vgl. lat. ûnicus.<nb1> asl. inok&u-short; einig, allein, Mönch. Mit anderem Suffixe g. ainakls einzeln, einsam, vgl. an. einka besonderer, ekkja Witwe.</nb1></entry>

<entry id="b0003:5" indentation="2" parent="3:3" click="153,943" semantic_class="nu"><lm>ainalibi</lm> elf. g. ainlif; an. ellifu; as. êlle&b-bar;an, ags. <oe>endlufon</oe> (engl. eleven); ahd. einlef, mhd. einlif, einlef, eilef, elf, mhd. eilf, elf. Vgl. lit. vën&u-oring;-lika elf. (Wahrscheinlich ursprünglich ainalihva, was nach der Wz. lib umgebildet wurde, nachdem die Wz. lihv ihre ursprüngliche Bedeutung »übrig lassen, übrig bleiben« verloren hatte).</entry>

<ergentry id="b0003:5b" indentation="1"><lm>*aibô</lm> f. Gau. ahd. -eiba als zweites Glied in zusammengesetzten Ortsnamen, z. B. Wetareiba, langob. -aib. Vgl. skr. íbha m. n. Gesinde, Hausgenossenschaft, Familie (Lidén, St. z. ai. n. vergl. Sprachges. 52).</ergentry>

<entry id="b0003:6" indentation="1" click="83,1223"><lm>aibra</lm> bitter, heftig. ags. <oe>âfor</oe> harsch, heftig; ahd. aipar, eipar, eiber (bei Notk. eiver, eifir) acerbus, amarus, horridus. Vgl. lit. aibrùmas das Wässern im Munde.</entry>

<entry id="b0003:7" indentation="1" click="83,1373"><lm>air</lm> adv. frühe. g. air adv. frühe, comp. airis früher; an. âr frühe: as. êr, ags. <oe>âr</oe> frühe und <oe>&aelig-circ;r</oe> (= g. airis) früher, adv., praep., conj.: ahd. êr, mhd. êr, gewöhnlich ê, adv. früher, eher, praep. m. dat. gen. vor, conj. eher, als, bis.<nb1> Dazu an â&d-bar;r comp. ehe, eher (aus airþr?).</nb1> Aus ig. aier(i). Vgl. gr. <gr><new>&#x1F04;&#x0304;&#x03C1;&#x03B9;-&#x03C3;&#x03C4;&#x03BF;&#x03BD;</new><old>a_)'ri-ston</old></gr> Frühstück (aus <gr><new>&#x03B1;&#x006A;&#x03B5;&#x03C1;&#x03B9;-</new><old>ajeri-</old></gr>); Dehnstufe in <gr><new>&#x1F20;&#x03C1;&#x03B9;</new><old>h)ri</old></gr> frühe (aus <gr><new>&#x1FB1;&#x006A;&#x03B5;&#x03C1;&#x03B9;</new><old>a_jeri</old></gr>). Lokativ zu zend. ayare Tag.</entry>

<entry id="b0003:8" indentation="1" click="90,1660" semantic_class="sh"><lm>airô</lm> f. Ruder. an. âr f. Ruder; ags. <oe>âr</oe> f. dass. (engl. oar). Lit. va&i-tilde;ras m. ein langes Ruder ist aus dem Nord. entlehnt.</entry>

<entry id="b0003:9" indentation="1" click="83,1763"><lm>airu</lm> m. Bote, Diener. g. airus m. Bote, Diener; an. ârr pl. ærir und ârar m. dass.; as. êru, ags. <oe>âr</oe> m. dass. Dazu got. airinôn Bote sein, an. ârna iter facere, (Unverwandt germ. &e-long;rundia (arundia) n. Botschaft, Auftrag = an. erindi, ørindi, as. ârundi, ags. <oe>&aelig-circ;rende</oe>, ahd. ârunti, n.; dies Wort gehört zu griech. <gr><new>(&#x1F51;&#x03C0;)&#x03B5;&#x03C1;&#x1F73;&#x03C4;&#x03B7;&#x03C2;</new><old>((u(p))ere'ths</old></gr> skr. aratí Diener, s. rô). Vielleicht von der Wz. i gehen.</entry>

<entry id="b0003:10" indentation="1" click="80,2040"><lm>ailian</lm> brennen. Vgl. aid. ags. <oe>&aelig-circ;lan</oe> brennen.</entry>

<entry id="b0003:11" indentation="2" parent="3:10" click="150,2086" second_id="b0004:1" second_click="53,156"><lm>ailida</lm>, <lm>ailda</lm> m. Feuer. an. eldr m. (aus ailda) Feuer; <pagebreak/> ags. <oe>&aelig-circ;led</oe> m. Feuer, Feuerbrand. Vgl. cymr. ailwyd f. Herd (aus ailêtâ).</entry>

<pageheader id="b0004:0" pagenum_click="50,60" upper_right_click="1186,136" lower_right_click="1200,2103">4 aiva - (au).</pageheader>

<entry id="b0004:2" indentation="1" click="53,253"><lm>aiva</lm> aevum. g. aivs lange Zeit, Ewigkeit, Zeit, diese Zeit, Welt, aiv adv. irgend einmal; an. æ, ei adv. immer, langær longaevus, æfi f. Lebenszeit; as. êo, io, gio adv., mndl. êwe Lebenszeit, ags. <oe>â</oe> adv.; ahd. êwa Ewigkeit, eo, io, adv., mhd. ie, nhd. je, ahd. nio, nhd. nie. Vgl. gr. <gr><new>&#x03B1;&#x1F30;&#x1F7D;&#x03BD;, &#x03B1;&#x1F30;&#x03B5;&#x1F77;</new><old>ai)w'n, ai)ei'</old></gr>. - lat. aevum. - ir. aes m. - s. âyus n. Leben, Lebensdauer, âyú lebendig, beweglich.<nb1> ags. <oe>êce</oe> ewig (g. ajuk-).</nb1> Vgl. germ. aja-k in g. ajukdûþs Ewigkeit.</entry>

<entry id="b0004:3" indentation="1" click="53,526" semantic_class="so"><lm>aiva</lm> m., <lm>aivô</lm> f. (aus aigvô?) Gesetz. as. êo, êu m. Gesetz, afries. êwe, ê f., ags. <oe>&aelig-circ;</oe>, <oe>&aelig-circ;w</oe> f. Gesetz, Religion, heiliger Brauch, Ehe; ahd. êwa, êa f. Gesetz, Norm, Bündnis, Ehe, mhd. êwe, ê, nhd. Ehe. Vgl. lat. ae&q-bar;uus <QUESTIONABLE/> gerecht, billig. Oder zu skr. eva m. Lauf, Gang, pl. das Gebahren, Handlungsweise, Gewohnheit. (Wurzel i gehen)?</entry>

<entry id="b0004:4" indentation="1" click="53,753">(<lm>ais</lm>) 1. fordern, heischen. Vgl. lit. jëszkóti suchen, asl. iskati. - skr. icchati sucht, icchâ f. Wunsch, zend. içaiti sucht. - gr. <gr><new>&#x1F35;&#x03BC;&#x03B5;&#x03C1;&#x03BF;&#x03C2;</new><old>i('meros</old></gr> (aus <gr><new>&#x1F30;&#x03C3;&#x03BC;&#x03B5;&#x03C1;&#x03BF;&#x03C2;</new><old>i)smeros</old></gr>). - lat. aerusco bitte.</entry>

<entry id="b0004:5" indentation="2" parent="4:4" click="126,893"><lm>aiskôn</lm> fordern, suchen, heischen. as. êscôn, êscian fordern, ags. <oe>âscian</oe>, <oe>âcsian</oe> versuchen, fordern, fragen, engl. ask, afries. âskia; ahd. eiscôn forschen, fragen, fordern, mhd. eischen, nhd. heischen. - Dazu sbst. aiskiôn in ags. <oe>&aelig-circ;sce</oe> f. Untersuchung; ahd. eisca f. Forderung. Vgl. asl. iska f. Forderung. - skr. icchâ f. Wunsch, Forderung.</entry>

<entry id="b0004:6" indentation="1" click="53,1166">(<lm>ais</lm>) 2. scheuen, verehren, schonen. Vgl. gr. <gr><new>&#x03B1;&#x1F34;&#x03B4;&#x03BF;&#x03BC;&#x03B1;&#x03B9;</new><old>ai)'domai</old></gr> (aus aisd-) scheue, verehre. - lat. aestimare (aus aisditumare). Schwundstufe in ved. î&d-udot;e ich verehre.</entry>

<entry id="b0004:7" indentation="2" parent="4:6" click="126,1306" semantic_class="i2"><lm>aizô</lm> f. Schonung, Ehre. an. Eir f. Göttin der Heilkunde, eig. Schonung; ags. <oe>âr</oe> f. Wohlthat, <PREMODERN_SPELLING mod="Wohltat"/> Schonung, Ehre, afries. êre; ahd. êra, mhd. êre, nhd. Ehre f.</entry>

<entry id="b0004:8" indentation="3" parent="4:7" click="196,1450"><lm>aizian</lm>, <lm>aizôn</lm>, <lm>aizên</lm> schonen. an. eira r&d-bar;a schonen, verschonen, eir&d-bar; f. Schonung, eirinn nachsichtig; ags. <oe>ârian</oe> schonen, ehren, afries. âria, êria ehren; ahd. êrôn, êrên ehren, beschenken, nhd. ehren.</entry>

<entry id="b0004:9" indentation="2" parent="4:6" click="130,1633"><lm>aistên</lm> achten. g. aistan aida achten. Vgl. gr. <gr><new>&#x03B1;&#x1F34;&#x03B4;&#x03BF;&#x03BC;&#x03B1;&#x03B9;</new><old>ai)'domai</old></gr>. - lat. aestimare. - ved. î&d-udot;e.</entry>

<ergentry id="b0004:9b" indentation="1" ><lm>ais</lm> 3, <lm>aisôn</lm>. an. eisa mit Gewalt einherfahren. Vgl. skr. e&s-udot;ati in rasche Bewegung setzen, schleudern, vordringen, e&s-udot;a das Eilen, î&s-udot;a&n-udot;a eilend. Hierzu stellt Holthausen (I. F. XX 320) ags. <oe>ofost</oe> Eile, Eifer (&gt; ab-aist-). Vgl. zend. aêshma Zorn, gr. <gr><new>&#x03BF;&#x1F36;&#x03BC;&#x03B1;</new><old>oi)=ma</old></gr>.</ergentry>

<entry id="b0004:10" indentation="1" click="60,1730"><lm>aiza</lm> (aus aiz) n. Erz. g. ais g. aizis Erz, Geld; an. eir n. Erz, Kupfer; as. êr, ags. <oe>âr</oe>, <oe>&aelig-circ;r</oe> n. Erz; ahd. mhd. êr n. Erz, Eisen. Vgl. lat. aes g. aeris n. Erz. - s. ayas n. Erz, Metall; zend. aya&n-odot;h- n. Metall, Eisen. - Vgl. îsarna.</entry>

<entry id="b0004:11" indentation="2" parent="4:10" click="133,1916"><lm>aizîna</lm> ehern. ags. <oe>æren</oe>, as. ahd. mhd. êrîn, nhd. ehern. Vgl. lat. ahênus, aênus (aus ajesno) ehern. - zend. aya&n-odot;haêna metallen, eisern.</entry>

<entry id="b0004:12" indentation="1" click="60,2043">(<lm>au</lm>) 1. mangeln, leer sein. Vgl. va. Vgl. gr. <gr><new>&#x03B5;&#x1F56;&#x03BD;&#x03B9;&#x03C2;</new><old>eu)=nis</old></gr> beraubt. - skr. ûna mangelnd. - arm. unain leer.</entry>

<pageheader id="b0005:0" pagenum_click="1196,50" upper_right_click="1196,146" lower_right_click="1203,2110">auþa - augian. 5</pageheader>

<entry id="b0005:1" indentation="2" parent="4:12" click="126,146" semantic_class="i3"><lm>auþa</lm>, <lm>auþia</lm> öde (eig. part. praet.). g. auþa od. auþeis öde, wüst, leer, auþida f. Wüste; an. au&d-bar;r öde, leer; as ôthi, ags. <oe>íeþe</oe>; ahd. ôdi, mhd. &oelig;de öde, leer.</entry>

<entry id="b0005:2" indentation="3" parent="5:1" click="196,290"><lm>auþian</lm> öde machen. an. ey&d-bar;a öde machen, verwüsten, zerstören; ags. <oe>íeþan</oe> öde machen, verheeren; ahd. ôdjan, ôden. mhd. &oelig;den öde machen, nhd. ver-öden. - Vgl. auch ahd. ôdsen veröden.</entry>

<entry id="b0005:3" indentation="1" click="53,470">(<lm>au</lm>) 2. fördern. Vgl. gr. <gr><new>&#x1F10;&#x03BD;&#x03B7;&#x1F75;&#x03C2;</new><old>e)nhh's</old></gr> wohlwollend, mild (Homer) aus <gr><new>&#x1F10;&#x03BD;</new><old>e)n</old></gr> + av&e-long;s. - skr. ávas n. Gunst, Behagen, avati fördert, labt, ist hold. lat. avêre gesund sein. - ir. con-ói dient, hilft. Vgl. auch g. avi-liuþ Danksagung. Ig. Wurzel ave.</entry>

<entry id="b0005:4" indentation="2" parent="5:3" click="130,660"><lm>auþia</lm> leicht, bequem, an. au&d-bar;- in Zusammensetzungen leicht; as. ôthi, ôdi, ags. <oe>íeþe</oe>, <oe>éaþe</oe> leicht, bequem; ahd. ôdi dass.</entry>

<entry id="b0005:5" indentation="3" parent="5:4" click="196,760"><lm>auþa-môda</lm> m. Demut, adj. demütig, <lm>auþa-môdia</lm> demütig. as. ôdhmôdi demütig, ags. <oe>éaþmôd</oe> m. Demut, adj. willig; ahd. ôdmuati demütig.</entry>

<entry id="b0005:6" indentation="1" click="53,896"><lm>au-k</lm> adv. aber, auch. g. auk conj. denn, aber; an. auk, später ok auch, und; as. ôk, ags. <oe>éac</oe> auch; ahd. auh, ouh, mhd. ouch auch, und noch, aber, nhd. auch. Vgl. gr. <gr><new>&#x03B1;&#x1F50;, &#x03B1;&#x1F50;-&#x03B3;&#x03B5;</new><old>au), au)-ge</old></gr> (=auk) wiederum, <gr><new>&#x03B1;&#x1F56;-&#x03D1;&#x03B9;&#x03C2;, &#x03B1;&#x1F56;-&#x03C4;&#x03B9;&#x03C2;</new><old>au)=-qis, au)=-tis</old></gr> wieder, zurück, <gr><new>&#x03B1;&#x1F50;-&#x03C4;&#x03B5;</new><old>au)-te</old></gr> wieder, aber. - lat. au-t oder, au-tem aber, osk. au-ti aber.</entry>

<entry id="b0005:7" indentation="1" click="56,1130"><lm>aukan</lm> <lm>eauk</lm> <lm>aukana</lm> mehren. Vgl. vahsan. g. aukan aíauk mehren, sich mehren; an. auka jôk und auka a&d-bar;a mehren, hinzufügen; as. ôkian schw. vb. (part. praet. ôkan), ags. <oe>éacian</oe> schw. vb. (part. <oe>éacen</oe>) zunehmen; ahd. auhhôn, ouhhôn, ouchôn hinzufügen, mehren. Vgl. lit. áugu áugti wachsen, zunehmen. - lat. augeo auxi.</entry>
